AWSTemplateFormatVersion: "2010-09-09"
Description: |
 This CFN template deploys roman numbers app.
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dc2d3e4c0f9ebd18
      InstanceType: t2.micro
      KeyName: ec2_key
      SecurityGroups:
        - allow ssh and http
      Tags:
        - Key: Name
          Value: Adam
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          yum update -y
          yum install -y git
          mkdir /home/ec2-user/project
          chmod -R 777 /home/ec2-user/project
          cd /home/ec2-user/project
          git clone https://github.com/ybaslayan/Projects.git
          pip3 install flask
          cd /home/ec2-user/project/Project-001-Roman-Numerals-Converter
          python3 app.py